global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: jeecg-boot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["jeecg-boot:7001"]
  - job_name: device-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["device-service:8091"]
  - job_name: model-service
    metrics_path: /metrics
    static_configs:
      - targets: ["model-service:8000"]
  - job_name: pias
    metrics_path: /metrics
    static_configs:
      - targets: ["pias:8010"]
