services:
  software-db:
    ports:
      - "127.0.0.1:3306:3306"

  hardware-db:
    ports:
      - "127.0.0.1:5432:5432"

  kafka:
    ports:
      - "127.0.0.1:29092:29092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  nacos:
    ports:
      - "127.0.0.1:8848:8848"
      - "127.0.0.1:9848:9848"

  grafana:
    ports:
      - "127.0.0.1:3000:3000"

  prometheus:
    ports:
      - "127.0.0.1:9090:9090"

networks:
  backend:
    internal: false
  data:
    internal: false
  observability:
    internal: false
